---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: felix
    name: postgres-pod
 spec:
   containers:
     name: postgres
     image: postgres
     env:
       - name: POSTGRE_PASSWORD
         value: felix
       - name: POSTGRES_USER
         value: myuser
       - name: POSTGRES_DB
         value:  mydb
     ports:
       - containerPort: 5432
...
