---
apiVersion: v1
kind: Service
metadata:
  name: results-app-service
  labels:
    author: felix
    name: result-app-service

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    author: felix
    name: result-app-pod
...